### ISSUE TITLE
RuleInput class needs nullable fields

### ISSUE THREAD

**Issue by Dylan-Riley** [theanticrumpet/CounterpointGenerator#9]
Replace the int fields in `IRules.cs`'s with note objects and other nullable fields to accommodate not always needing all input.

Waiting (no rush) on https://github.com/theanticrumpet/CounterpointGenerator/pull/8

**Comment by Dylan-Riley** [comment]
Though, since rule application is all internal anyways and not exposed to the user may be fine as long as all fields get properly initialized? Will need testing, look into as code develops.

**Comment by aditink** [comment]
Yes, I think this will only be needed once there are enough rules that diverge in requirements enough that there are fields that you would want set to null most of the time.

**Comment by Dylan-Riley** [comment]
Has run with null fields just fine, seems to be a non-issue since rules should be designed to not use more than the exact input they need.
